Docs
rjmalves/sintetizador-dessem pull request #8
Opened 2023-10-05 19:08 UTC by rjmalves

2023-10-05 23:14 UTC, marianasnoel requested changes

2023-10-05 23:14 UTC, marianasnoel commented on docs/source/reference/commands.rst
> +    >>>   execucao  Realiza a síntese dos dados da execução do DESSEM.
Retirar, pois ainda não tem opção de comando de execução

2023-10-05 23:14 UTC, marianasnoel commented on examples/README.rst
> +Nesta seção estão descritos alguns exemplos de casos de uso para o `sintetizador-newave`.
Corrigir para sintetizador-dessem

2023-10-05 23:14 UTC, marianasnoel commented on docs/source/conf.py
> +project = "sintetizador-newave"
Trocar para sintetizador-dessem

2023-10-06 12:04 UTC, rjmalves commented on docs/source/reference/commands.rst
> +    >>>   execucao  Realiza a síntese dos dados da execução do DESSEM.
Feito em ed1d17e424773574a727b579af7d07c5e8a4bcaf

2023-10-06 12:04 UTC, rjmalves commented on examples/README.rst
> +Nesta seção estão descritos alguns exemplos de casos de uso para o `sintetizador-newave`.
Feito em ed1d17e424773574a727b579af7d07c5e8a4bcaf

2023-10-06 12:04 UTC, rjmalves commented on docs/source/conf.py
> +project = "sintetizador-newave"
Feito em ed1d17e424773574a727b579af7d07c5e8a4bcaf

2023-10-06 12:09 UTC, marianasnoel approved these changes

2023-10-06 12:09 UTC, merged